package mindustry.core.typedefs;

public class ExportedClasses {
    public static String[][] exported = new String[][]{
            {"arc"},
            {"arc", "collection"},
            {"arc", "func"},
            {"arc", "graphics"},
            {"arc", "graphics", "g2d"},
            {"arc", "math"},
            {"arc", "scene"},
            {"arc", "scene", "actions"},
            {"arc", "scene", "event"},
            {"arc", "scene", "style"},
            {"arc", "scene", "ui"},
            {"arc", "scene", "ui", "layout"},
            {"arc", "scene", "utils"},
            {"arc", "util"},
            {"mindustry"},
            {"mindustry", "ai"},
            {"mindustry", "content"},
            {"mindustry", "core"},
            {"mindustry", "ctype"},
            {"mindustry", "editor"},
            {"mindustry", "entities"},
            {"mindustry", "entities", "bullet"},
            {"mindustry", "entities", "effect"},
            {"mindustry", "entities", "traits"},
            {"mindustry", "entities", "type"},
            {"mindustry", "entities", "type", "base"},
            {"mindustry", "entities", "units"},
            {"mindustry", "game"},
            {"mindustry", "gen"},
            {"mindustry", "graphics"},
            {"mindustry", "input"},
            {"mindustry", "maps"},
            {"mindustry", "maps", "filters"},
            {"mindustry", "maps", "generators"},
            {"mindustry", "maps", "zonegen"},
            {"mindustry", "type"},
            {"mindustry", "ui"},
            {"mindustry", "ui", "dialogs"},
            {"mindustry", "ui", "fragments"},
            {"mindustry", "ui", "layout"},
            {"mindustry", "world"},
            {"mindustry", "world", "blocks"},
            {"mindustry", "world", "blocks", "defense"},
            {"mindustry", "world", "blocks", "defense", "turrets"},
            {"mindustry", "world", "blocks", "distribution"},
            {"mindustry", "world", "blocks", "liquid"},
            {"mindustry", "world", "blocks", "logic"},
            {"mindustry", "world", "blocks", "power"},
            {"mindustry", "world", "blocks", "production"},
            {"mindustry", "world", "blocks", "sandbox"},
            {"mindustry", "world", "blocks", "storage"},
            {"mindustry", "world", "blocks", "units"},
            {"mindustry", "world", "consumers"},
            {"mindustry", "world", "meta"},
            {"mindustry", "world", "meta", "values"},
            {"mindustry", "world", "modules"},
            {"mindustry", "world", "producers"}
    };
}
